### ISSUE TITLE
上传图片无法使用

### ISSUE THREAD

**Issue by ca-ssiee** [lalz001/pymindmap#1]
点击上传图片，上传本地xmind导出的png图片，一直报错404
![image](https://user-images.githubusercontent.com/24838062/70213861-52717080-1775-11ea-8564-3b81d902def6.png)

**Comment by lalz001** [comment]
这个报错可能性很多，可以加qq聊一下？qq：1431822586

**Comment by ca-ssiee** [comment]
有兴趣开发导入和导出 支持本地文件吗？excel的

**Comment by lalz001** [comment]
沟通后没有问题~
